### PR TITLE
Update to 1.15.2 and add myself as maintainer

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@davehunt this seems now ready to be merged. 👍

**Review by davehunt — APPROVED** [review]
Changes look fine to me, but I have no idea what the impact of merging this is. If someone can reassure me, or let me know where I can check for success, I'd be happy to hit the big green button.

**Comment by nicoddemus** [comment]
@davehunt this will basically publish the package. It is the correct thing to do because all I did was update the package version. 👍

**Comment by jakirkham** [comment]
This will release a new package and add @nicoddemus as a maintainer. Does that make sense @davehunt?

**Comment by davehunt** [comment]
@jakirkham yep, sounds good!

**Comment by nicoddemus** [comment]
@davehunt if you are OK with it could you please merge the PR then? 😁

**Comment by nicoddemus** [comment]
Thanks @davehunt!

**Pull request merged**
