### PR TITLE
Update to 0.16.0

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @birdsarah! Thanks for the update.

In the future please open PRs from your fork: conda-forge is configured so builds in any branches of the feedstock repository publish the package automatically, so we have published linux and windows packages already while we wait for Travis.

In this case it won't really matter I think because the update was trivial, but in more complicated cases it might happen that we publish a version which works only in some of the supported platforms. 👍

**Comment by birdsarah** [comment]
"conda-forge is configured so builds in any branches of the feedstock repository publish the package automatically"

who know?! thanks so much for the feedback @nicoddemus

**Comment by ocefpaf** [comment]
> "conda-forge is configured so builds in any branches of the feedstock repository publish the package automatically"

That is a limitation we have due to the use of CIs to build and upload and how the authorization tokens work. If you have any suggestion to work around that we would love to know. However, we are now using branches to manage legacy versions or release candidates, so any possible solution should use some kind of whitelist to allow those branches to function properly.

**Comment by nicoddemus** [comment]
> However, we are now using branches to manage legacy versions or release candidates, so any possible solution should use some kind of whitelist to allow those branches to function properly.

If we whitelist `master` and some other naming scheme for other branches? For example `publish-.*` or `prod-.*` publish packages, any other branches don't.

**Comment by ocefpaf** [comment]
> If we whitelist `master` and some other naming scheme for other branches? For example `publish-.*` or `prod-.*` publish packages, any other branches don't.

That could work. I know that some people discussed some ideas in the past, not sure what were the conclusions though. I'll try to find the threads.

**Pull request merged**
