### PR TITLE
Fix run requirements

### PR DESCRIPTION
**Pull request by lvoliveira**
Version 2.0 requires pytest>=5.0 on the setup.py

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
Great, thanks!

**Comment by nicoddemus** [comment]
@ocefpaf could you please mark the package with build number 0 as "broken", `pytest-html-2.0.0-py_0.tar.bz2`? It contains wrong run requirements unfortunately.

**Comment by ocefpaf** [comment]
I'm away and with limited access to my laptop (lost my charger adapter). Can someone from @conda-forge/core address that request? (I don't have my anaconda.org password on my cellphone :-)

**Comment by nicoddemus** [comment]
Thanks @ocefpaf! 👍

**Comment by jjhelmus** [comment]
I moved `pytest-html-2.0.0-py_0.tar.bz2` to the broken label.

**Comment by nicoddemus** [comment]
Thanks @jjhelmus!

**Pull request merged**
